### ISSUE TITLE
다른 날짜의 요일이 잘못 표기되는 버그

### ISSUE THREAD

**Issue by ghost** [GrasshopperBears/kaifood#1]
![image](https://user-images.githubusercontent.com/84287503/149846277-8dfdab54-2125-4f59-8452-010363ec38f5.png)

https://github.com/GrasshopperBears/kaifood/blob/ab435f028c7a45a8eb4fd214d767ca1fd7764b1d/client/src/components/restaurant/RestaurantInsideDaily.jsx#L27

**Comment by GrasshopperBears** [comment]
제보 감사합니다. 수정/배포 완료했습니다.
이슈는 닫겠습니다 :)
